local add = hunger_ng.functions.add_hunger_data

add('ethereal:strawberry', { satiates = 1.0 })
add('ethereal:seaweed', { satiates = 1.0 })
add('ethereal:bamboo_sprout', { satiates = 1.0 })
add('ethereal:fern_tubers', { satiates = 1.0, heals = 1 })
add('ethereal:wild_onion_plant', { satiates = 1.0 })
add('ethereal:mushroom_soup', { satiates = 3.0 })
add('ethereal:yellowleaves', { satiates = 1.0, heals = 1})
add('ethereal:banana', { satiates = 1.0 })
add('ethereal:orange', { satiates = 1.0 })
add('ethereal:pine_nuts', { satiates = 1.0 })
add('ethereal:banana_bread', { satiates = 3.0 })
add('ethereal:coconut_slice', { satiates = 2.0 })
add('ethereal:golden_apple', { satiates = 10.0, heals = 10 })
add('ethereal:hearty_stew', { satiates = 5.0 })
add('ethereal:bucket_cactus', { satiates = 2.0 })
add('ethereal:firethorn_jelly', { satiates = 3.0 })
add('ethereal:fish_raw', { satiates = 1.0 })
add('ethereal:fish_cooked', { satiates = 3.0 })
add('ethereal:sashimi', { satiates = 3.0 })